object NameSpace {
    const val app = "com.timtam.moview"
    const val commonAndroid = "com.timtam.common_android"
    const val commonKotlin = "com.timtam.common_kotlin"
    const val localInteractor = "com.timtam.local_interactor"
    const val remoteInteractor = "com.timtam.remote_interactor"
    const val navigation = "com.timtam.navigation"
    const val uikit = "com.timtam.uikit"
    const val featureHelper = "com.timtam.feature_helper"
    const val featureInitial = "com.timtam.initial"
    const val featureInitialContract = "com.timtam.initial_contract"
    const val featureHome = "com.timtam.home"
    const val featureReview = "com.timtam.review"
    const val featureCollection = "com.timtam.collection"
}
